### PR TITLE
Fixed typos and cleaned up one Smalltalk method

### PR DESCRIPTION
**Pull request by norbertf**
Apart from the typos in  book/04-NeuralNetwork/04-chapter.markdown I cleaned up the method
"NNetwork>>train: someInputs desiredOutputs: desiredOutputs":
All the local variables and the "collect:" were superfluous

### CODE REVIEW

**Review by bergel — APPROVED** [review]

**Review by bergel — APPROVED** [review]

**Review by bergel — APPROVED** [review]

**Comment by bergel** [comment]
Thanks! This is great!

**Comment by bergel** [comment]
Thanks Norbert. I added your name in the ack section of  https://agileartificialintelligence.github.io

Your review is very valuable!

Alexandre

**Comment by norbertf** [comment]
No problem. I thank you for writing this! I will continue with the book and give you more feedback.
So far I am very pleased with the new Pharo environment, it starts to become very useable.
If I can help in any other way (e.g. testing) let me know.

**Comment by norbertf** [comment]
I meant: "thank you for writing this book"

**Pull request merged**
